baseURL = "https://blog.jobtechdev.se/"
languageCode = "en-us"
title = "Öppna data och källkod"
theme = "kube"
description = "Förbättra matchningen på arbetsmarknaden genom att dela öppna data och teknik"
Paginate = 4

publishDir = "public"

[Params]
  RSSLink = "/index.xml"
  author = "JobTech Dev" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "contact@jobtechdev.se"

#[[menu.main]]
#    name = "API"
#    weight = -100
#    url = "/docs/"
[[menu.main]]
    name = "Blogg"
    weight = -100
    url = "/blog/"
#[[menu.main]]
#    name = "Kontakt"
#    weight = -100
#    url = "/faq/"
